build:
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -U"
    MAVEN_IMAGE: maven:3.6.0
  only:
    - master
  cache:
    paths:
      - .m2/repository

  stage: build
  image: $MAVEN_IMAGE-jdk-8
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy -X -Dexec.skip -DskipTests'
  artifacts:
    paths:
      - essim-engine/target/essim.jar

deploy:
  only:
    - master
  dependencies:
    - build
  variables:
    CONTAINER_IMAGE: $GEIS_REGISTRY/$CI_PROJECT_NAME
  stage: deploy
  image: docker:stable
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $GEIS_REGISTRY
  script:
    - docker build -t $CONTAINER_IMAGE:latest essim-engine/.
    - docker tag $CONTAINER_IMAGE:latest $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
