build:
  variables:
    MAVEN_IMAGE: maven:3.6.0
  only:
    - master
  cache:
    paths:
      - .m2/repository

  stage: build
  image: $MAVEN_IMAGE-jdk-8
  script:
    - 'mvn package -X'
  artifacts:
    paths:
      - essim-engine/target/essim.jar

deploy:
  only:
    - master
  dependencies:
    - build
  variables:
    CONTAINER_IMAGE: $GEIS_REGISTRY/$CI_PROJECT_NAME
  stage: deploy
  image: docker:stable
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $GEIS_REGISTRY
  script:
    - docker build -t $CONTAINER_IMAGE:latest essim-engine/.
    - docker tag $CONTAINER_IMAGE:latest $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
