#%RAML 1.0

types:

  Status:
    enum: [CREATED, RUNNING, COMPLETE, ERROR]
    
  TimeDuration:
    enum: [SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, YEAR]
    
  OrderPreference:
    enum: [FIRST, LAST]
  
  TimeStep:
    type: object
    properties:
      value: number
      unit: TimeDuration

  CreatedStatus:
    type: object
    properties:
      status: Status
      id: string
  
  RunningStatus:
    type: object
    properties:
      status: Status
      progress: number
  
  ErrorStatus:
    type: object
    properties:
      status: Status
      description: string
  
  TransportNetwork:
    type: object
    properties:
      name: string
      networkHTMLDiag: string
  
  ExternalSolver:
    type: object
    properties:
      name: string
      url: string
      orderPreference?: OrderPreference
          
  KPIModule:
    type: object
    properties:
      id: string
      result?: string
      config: object
  
  RemoteKPIModule:
    type: object
    properties:
      kafkaURL: string
      modules: KPIModule[]

  EssimSimulation:
    type: object
    properties:
      esdlContents: string
      user: string
      scenarioID: string
      simulationDescription: string
      startDate: datetime
      endDate: datetime
      timeStep: TimeStep
      influxURL?: string
      natsURL?: string
      mqttURL?: string
      kafkaURL?: string
      externalSolvers?: ExternalSolver[]
      kpiModule?: RemoteKPIModule
      simRunDate?: datetime
      transport?: TransportNetwork[]
      dashboardURL?: string
      loadAnimationJSON?: string
      nodeConfig?: NodeConfiguration[]

  NodeConfiguration:
    type: object
    properties:
      esdlNodeId: string
      remoteNodeLogic: boolean
      mqttHost: string
      mqttPort: integer
      mqttTopic: string
  
  KPIModuleInfo:
    type: object
    properties:
      calculator_id: string
      title: string
      description: string
      config_config: object
      sample_output: string
      kafka_consumer_group: string
      kafka_client: string
      status: string
      up_since: datetime
  