version: '3'

networks:
  essim_net:

services:
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - mongo-storage:/data/db
    networks:
     - essim_net

  influxdb:
    image: influxdb:1.7
    ports:
      - 8086:8086
      - 8998:8088
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
     - essim_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=e$$$$im4life
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
     - essim_net

  essim:
    image: ci.tno.nl/essim/open-sourced-essim/essim-engine:master
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - CONSOLE_LOG_LEVEL=debug
      - EMISSION_MANAGER_ENABLE=false
      - FILE_LOG_LEVEL=debug
      - GRAFANA_ADMIN_PASSWORD=e$$$$im4life
      - GRAFANA_ADMIN_USER=admin
      - GRAFANA_EXTERNAL_URL=http://localhost:3000
      - GRAFANA_INTERNAL_URL=http://grafana:3000
      - HTTP_SERVER_HOSTNAME=0.0.0.0
      - HTTP_SERVER_PATH=essim
      - HTTP_SERVER_PORT=8081
      - HTTP_SERVER_SCHEME=http
      - LOG_FILE_LOCATION=logs
      - LOG_FILES_SIZE_CAP=2GB
      - MAX_LOG_FILE_SIZE=10MB
      - MAX_LOG_HISTORY_DAYS=60
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - PROFILE_QUERY_TIMEOUT=120
    networks:
      - essim_net

volumes:
  grafana-storage:
  influxdb-storage:
  mongo-storage:
