version: '3'

networks:
  mapeditor-net:
    external:
      name: mapeditor-net

services:
  essim-engine:
#   image: ci.hesi.energy:5000/essim-engine:latest
    build: .
    ports:
     - 8112:8112
    environment:
     - HTTP_SERVER_SCHEME=http
     - HTTP_SERVER_HOSTNAME=0.0.0.0
     - HTTP_SERVER_PORT=8112
     - HTTP_SERVER_PATH=essim
     - MONGODB_HOST=mongo
     - MONGODB_PORT=27017
     - GRAFANA_ADMIN_USER=admin
     - GRAFANA_ADMIN_PASSWORD=admin
    deploy:
      placement:
        constraints:
          - node.labels.function != dbs-only
    networks:
     - mapeditor-net

  nats:
    image: ci.hesi.energy:5000/nats-server:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    networks:
     - mapeditor-net


