version: '3'

networks:
  net:
    driver: overlay

services:
  essim-engine:
    image: ci.tno.nl/essim/open-sourced-essim/essim-engine:latest
    ports:
     - 8112:8112
    environment:
     - HTTP_SERVER_SCHEME=http
     - HTTP_SERVER_HOSTNAME=0.0.0.0
     - HTTP_SERVER_PORT=8112
     - HTTP_SERVER_PATH=essim
     - MONGODB_HOST=mongo
     - MONGODB_PORT=27017
     - GRAFANA_ADMIN_USER=admin
     - GRAFANA_ADMIN_PASSWORD=admin
     - GRAFANA_INTERNAL_URL=http://grafana:3000
     - GRAFANA_EXTERNAL_URL=http://localhost:3000
    deploy:
      placement:
        constraints:
          - node.labels.function != dbs-only
    networks:
     - net

  nats:
    image: ci.hesi.energy:5000/nats-server:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    networks:
     - net

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 0.0.0.0:27018:27017
    deploy:
      placement:
        constraints:
          - node.labels.function != dbs-only
    volumes:
      - mongo-storage:/data/db
    networks:
     - net

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
      - 8998:8088
    volumes:
      - influxdb-storage:/var/lib/influxdb
    deploy:
      placement:
        constraints:
          - node.labels.function == dbs-only
    networks:
     - net

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=https://essim-dashboard.hesi.energy
      - GF_SECURITY_ALLOW_EMBEDDING=True
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_AUTH_DISABLE_LOGIN_FORM=True
      - GF_AUTH_BASIC_ENABLED=False
      - GF_AUTH_OAUTH_AUTO_LOGIN=True
      - GF_AUTH_GENERIC_OAUTH_ENABLED=True
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=True
      - GF_AUTH_GENERIC_OAUTH_NAME=Auth0
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=essim-dashboard
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=7edfad6c-2ac4-4c7a-a725-fe7ffa032049
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://idm.hesi.energy/auth/realms/esdl-mapeditor/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://idm.hesi.energy/auth/realms/esdl-mapeditor/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://idm.hesi.energy/auth/realms/esdl-mapeditor/protocol/openid-connect/userinfo

    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.labels.function == dbs-only
    networks:
     - net


volumes:
  grafana-storage:
  influxdb-storage:
  mongo-storage:
